### ISSUE TITLE
Faster neighbor list

### ISSUE THREAD

**Issue by peastman** [Exscientia/physicsml#21]
I find that building neighbor lists is responsible for a significant fraction of the training time.  Here is a trace of a couple of training steps for a tensornet model with one interaction layer (running on CPU, since I'm having trouble getting tracing working with the GPU).

![Screenshot 2024-03-05 at 9 04 51 AM](https://github.com/Exscientia/physicsml/assets/4379786/ddc48954-9004-4d0d-97c3-2113a44ab422)

The part shown as "enumerate(DataLoader) is almost all spent building neighbor lists.

![Screenshot 2024-03-05 at 9 05 50 AM](https://github.com/Exscientia/physicsml/assets/4379786/5d100810-c53f-47db-aedd-25fea10e8340)

It uses a voxel algorithm to build neighbor lists.  That's an appropriate method for large systems with tens of thousands of atoms.  But most molecular datasets are made up of very small molecules with less than 100 atoms.  In that case, a simple O(n^2) routine is much faster.

There also are a number of well optimized neighbor list routines written in CUDA, such as in NNPOps and TorchMD-Net.  Using one of those could provide a further speedup.

The way the neighbor list routine is used also seems a bit odd to me.  `primitive_neighbor_list_torch()` computes the displacements and distances, which are the quantities needed for computing interactions.  But it doesn't return them.  Instead it discards them and returns the number of box vectors that need to be added to apply periodic boundary conditions to each pair.  That gets passed around through a few layers of code, and eventually passed to `compute_lengths_and_vectors()` which uses them to recompute the displacements and distances.  Returning them directly from the neighbor list instead of the cell shifts would save some duplicate computation.

**Comment by wardhaddadin1** [comment]
Hi Peter!

Thanks for this. I've also checked this locally and found the same. Actually, I find that the `primitive_neighbor_list_torch` is extremely slow even on large systems. Here is a little benchmark: 

Using `primitive_neighbor_list_torch` from `physicsml`: 

```
import torch

pos = 5 * torch.randn(1000, 3)

primitive_neighbor_list_torch(
        quantities="ijS",
        pbc=(False, False, False),
        cell=torch.eye(3),
        positions=pos,
        cutoff=5.0,
    )
```

time ~0.3s (mean of 10 runs)

Using an n^2 implementation, time ~ 0.02s (mean of 10)

Using the `from matscipy.neighbours import neighbour_list`, time ~ 0.09s (mean of 10)

When I chose the neighbourlist in physicsml, I just chose that one that was being used in the MACE repo (IIRC). But they've since changed to the `matscipy` one (probably because it's much faster).


What we can do now is: 

* Change to the `matscipy` one for when there is a need for pbcs.
* Use the n^2 implementation for when there are no pbcs. 


And lastly, for recomputing the distances and vectors: I naïvely assumed that if I didnt specify them, then they wont be computed (and then computing them on gpus would be faster), but seems like they are anyways... I'll leave this for another PR (because it will require changing model code at various places). 

Sorry about this! Will have a PR later today to fix the NL computation.
